baseURL = "https://github.com/RMProfit/blog/"
languageCode = "en-us"
title = "Robert Profit's Mostly UC Blog"

[[paige.feed.atom.authors]]
name = "Robert Profit"
email = "robert.profit82@gmail.com" 

[[module.imports]]
path = "github.com/willfaught/paige"

